services:
  backend:
    build: .
    container_name: backend-core
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_3aSeQW0qTPju@ep-cold-king-adyr1oj3-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
