"""add password_hash to users

Revision ID: 8f2d19f5ce3d
Revises: 123e3ff55d91
Create Date: 2025-10-26 20:40:04.454464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2d19f5ce3d'
down_revision: Union[str, Sequence[str], None] = '123e3ff55d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'editor', 'viewer', name='userrole'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
